// Assignment Code
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

function generatePassword(){
  console.log("generatePassword");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) first = "a";
  else if (rnum1 === 1) first = "b";
  else if (rnum1 === 2) first = "c";
  else if (rnum1 === 3) first = "d";
  else if (rnum1 === 4) first = "e";
  else if (rnum1 === 5) first = "f";
  else if (rnum1 === 6) first = "g";
  else if (rnum1 === 7) first = "h";
  else if (rnum1 === 8) first = "i";
  else if (rnum1 === 9) first = "j";
  else if (rnum1 === 10) first = "k";
  else if (rnum1 === 11) first = "l";
  else if (rnum1 === 12) first = "m";
  else if (rnum1 === 13) first = "n";
  else if (rnum1 === 14) first = "o";
  else if (rnum1 === 15) first = "p";
  else if (rnum1 === 16) first = "q";
  else if (rnum1 === 17) first = "r";
  else if (rnum1 === 18) first = "s";
  else if (rnum1 === 19) first = "t";
  else if (rnum1 === 20) first = "u";
  else if (rnum1 === 21) first = "v";
  else if (rnum1 === 22) first = "w";
  else if (rnum1 === 23) first = "x";
  else if (rnum1 === 24) first = "y";
  else if (rnum1 === 25) first = "z";
  else if (rnum1 === 26) first = "A";
  else if (rnum1 === 27) first = "B";
  else if (rnum1 === 28) first = "C";
  else if (rnum1 === 29) first = "D";
  else if (rnum1 === 30) first = "E";
  else if (rnum1 === 31) first = "F";
  else if (rnum1 === 32) first = "G";
  else if (rnum1 === 33) first = "H";
  else if (rnum1 === 34) first = "I";
  else if (rnum1 === 35) first = "J";
  else if (rnum1 === 36) first = "K";
  else if (rnum1 === 37) first = "L";
  else if (rnum1 === 38) first = "M";
  else if (rnum1 === 39) first = "N";
  else if (rnum1 === 40) first = "O";
  else if (rnum1 === 41) first = "P";
  else if (rnum1 === 42) first = "Q";
  else if (rnum1 === 43) first = "R";
  else if (rnum1 === 44) first = "S";
  else if (rnum1 === 45) first = "T";
  else if (rnum1 === 46) first = "U";
  else if (rnum1 === 47) first = "V";
  else if (rnum1 === 48) first = "W";
  else if (rnum1 === 49) first = "X";
  else if (rnum1 === 50) first = "Y";
  else if (rnum1 === 51) first = "Z";
  else if (rnum1 === 52) first = "0";
  else if (rnum1 === 53) first = "1";
  else if (rnum1 === 54) first = "2";
  else if (rnum1 === 55) first = "3";
  else if (rnum1 === 56) first = "4";
  else if (rnum1 === 57) first = "5";
  else if (rnum1 === 58) first = "6";
  else if (rnum1 === 59) first = "7";
  else if (rnum1 === 60) first = "8";
  else if (rnum1 === 61) first = "9";
  else if (rnum1 === 62) first = "!";
  else if (rnum1 === 63) first = "@";
  else if (rnum1 === 64) first = "#";
  else if (rnum1 === 65) first = "$";
  else if (rnum1 === 66) first = "%";
  else if (rnum1 === 67) first = "^";
  else if (rnum1 === 68) first = "&";
  else if (rnum1 === 69) first = "*";
  else if (rnum1 === 70) first = "(";
  else if (rnum1 === 71) first = ")";
  else if (rnum1 === 72) first = "-";
  else if (rnum1 === 73) first = "=";
  else if (rnum1 === 74) first = "_";
  else if (rnum1 === 75) first = "+";
  else if (rnum1 === 76) first = "[";
  else if (rnum1 === 77) first = "]";
  else if (rnum1 === 78) first = "{";
  else if (rnum1 === 79) first = "}";
  else if (rnum1 === 80) first = "|";
  else if (rnum1 === 81) first = ";";
  else if (rnum1 === 82) first = ":";
  else if (rnum1 === 83) first = "'";
  else if (rnum1 === 84) first = ",";
  else if (rnum1 === 85) first = ".";
  else if (rnum1 === 86) first = "/";
  else if (rnum1 === 87) first = "<";
  else if (rnum1 === 88) first = ">";
  else if (rnum1 === 89) first = "?";

  generateSecond()
}

function generateSecond(){
  console.log("generateSecond");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) second = "a";
  else if (rnum1 === 1) second = "b";
  else if (rnum1 === 2) second = "c";
  else if (rnum1 === 3) second = "d";
  else if (rnum1 === 4) second = "e";
  else if (rnum1 === 5) second = "f";
  else if (rnum1 === 6) second = "g";
  else if (rnum1 === 7) second = "h";
  else if (rnum1 === 8) second = "i";
  else if (rnum1 === 9) second = "j";
  else if (rnum1 === 10) second = "k";
  else if (rnum1 === 11) second = "l";
  else if (rnum1 === 12) second = "m";
  else if (rnum1 === 13) second = "n";
  else if (rnum1 === 14) second = "o";
  else if (rnum1 === 15) second = "p";
  else if (rnum1 === 16) second = "q";
  else if (rnum1 === 17) second = "r";
  else if (rnum1 === 18) second = "s";
  else if (rnum1 === 19) second = "t";
  else if (rnum1 === 20) second = "u";
  else if (rnum1 === 21) second = "v";
  else if (rnum1 === 22) second = "w";
  else if (rnum1 === 23) second = "x";
  else if (rnum1 === 24) second = "y";
  else if (rnum1 === 25) second = "z";
  else if (rnum1 === 26) second = "A";
  else if (rnum1 === 27) second = "B";
  else if (rnum1 === 28) second = "C";
  else if (rnum1 === 29) second = "D";
  else if (rnum1 === 30) second = "E";
  else if (rnum1 === 31) second = "F";
  else if (rnum1 === 32) second = "G";
  else if (rnum1 === 33) second = "H";
  else if (rnum1 === 34) second = "I";
  else if (rnum1 === 35) second = "J";
  else if (rnum1 === 36) second = "K";
  else if (rnum1 === 37) second = "L";
  else if (rnum1 === 38) second = "M";
  else if (rnum1 === 39) second = "N";
  else if (rnum1 === 40) second = "O";
  else if (rnum1 === 41) second = "P";
  else if (rnum1 === 42) second = "Q";
  else if (rnum1 === 43) second = "R";
  else if (rnum1 === 44) second = "S";
  else if (rnum1 === 45) second = "T";
  else if (rnum1 === 46) second = "U";
  else if (rnum1 === 47) second = "V";
  else if (rnum1 === 48) second = "W";
  else if (rnum1 === 49) second = "X";
  else if (rnum1 === 50) second = "Y";
  else if (rnum1 === 51) second = "Z";
  else if (rnum1 === 52) second = "0";
  else if (rnum1 === 53) second = "1";
  else if (rnum1 === 54) second = "2";
  else if (rnum1 === 55) second = "3";
  else if (rnum1 === 56) second = "4";
  else if (rnum1 === 57) second = "5";
  else if (rnum1 === 58) second = "6";
  else if (rnum1 === 59) second = "7";
  else if (rnum1 === 60) second = "8";
  else if (rnum1 === 61) second = "9";
  else if (rnum1 === 62) second = "!";
  else if (rnum1 === 63) second = "@";
  else if (rnum1 === 64) second = "#";
  else if (rnum1 === 65) second = "$";
  else if (rnum1 === 66) second = "%";
  else if (rnum1 === 67) second = "^";
  else if (rnum1 === 68) second = "&";
  else if (rnum1 === 69) second= "*";
  else if (rnum1 === 70) second = "(";
  else if (rnum1 === 71) second = ")";
  else if (rnum1 === 72) second = "-";
  else if (rnum1 === 73) second = "=";
  else if (rnum1 === 74) second = "_";
  else if (rnum1 === 75) second = "+";
  else if (rnum1 === 76) second = "[";
  else if (rnum1 === 77) second = "]";
  else if (rnum1 === 78) second = "{";
  else if (rnum1 === 79) second = "}";
  else if (rnum1 === 80) second = "|";
  else if (rnum1 === 81) second = ";";
  else if (rnum1 === 82) second = ":";
  else if (rnum1 === 83) second = "'";
  else if (rnum1 === 84) second = "<";
  else if (rnum1 === 85) second = ">";
  else if (rnum1 === 86) second = ",";
  else if (rnum1 === 87) second = ".";
  else if (rnum1 === 88) second = "/";
  else if (rnum1 === 89) second = "?";

  generateThird()
}

function generateThird(){
  console.log("generateThird");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) third = "a";
  else if (rnum1 === 1) third = "b";
  else if (rnum1 === 2) third = "c";
  else if (rnum1 === 3) third = "d";
  else if (rnum1 === 4) third = "e";
  else if (rnum1 === 5) third = "f";
  else if (rnum1 === 6) third = "g";
  else if (rnum1 === 7) third = "h";
  else if (rnum1 === 8) third = "i";
  else if (rnum1 === 9) third = "j";
  else if (rnum1 === 10) third = "k";
  else if (rnum1 === 11) third = "l";
  else if (rnum1 === 12) third = "m";
  else if (rnum1 === 13) third = "n";
  else if (rnum1 === 14) third = "o";
  else if (rnum1 === 15) third = "p";
  else if (rnum1 === 16) third = "q";
  else if (rnum1 === 17) third = "r";
  else if (rnum1 === 18) third = "s";
  else if (rnum1 === 19) third = "t";
  else if (rnum1 === 20) third = "u";
  else if (rnum1 === 21) third = "v";
  else if (rnum1 === 22) third = "w";
  else if (rnum1 === 23) third = "x";
  else if (rnum1 === 24) third = "y";
  else if (rnum1 === 25) third = "z";
  else if (rnum1 === 26) third = "A";
  else if (rnum1 === 27) third = "B";
  else if (rnum1 === 28) third = "C";
  else if (rnum1 === 29) third = "D";
  else if (rnum1 === 30) third = "E";
  else if (rnum1 === 31) third = "F";
  else if (rnum1 === 32) third = "G";
  else if (rnum1 === 33) third = "H";
  else if (rnum1 === 34) third = "I";
  else if (rnum1 === 35) third = "J";
  else if (rnum1 === 36) third = "K";
  else if (rnum1 === 37) third = "L";
  else if (rnum1 === 38) third = "M";
  else if (rnum1 === 39) third = "N";
  else if (rnum1 === 40) third = "O";
  else if (rnum1 === 41) third = "P";
  else if (rnum1 === 42) third = "Q";
  else if (rnum1 === 43) third = "R";
  else if (rnum1 === 44) third = "S";
  else if (rnum1 === 45) third = "T";
  else if (rnum1 === 46) third = "U";
  else if (rnum1 === 47) third = "V";
  else if (rnum1 === 48) third = "W";
  else if (rnum1 === 49) third = "X";
  else if (rnum1 === 50) third = "Y";
  else if (rnum1 === 51) third = "Z";
  else if (rnum1 === 52) third = "0";
  else if (rnum1 === 53) third = "1";
  else if (rnum1 === 54) third = "2";
  else if (rnum1 === 55) third = "3";
  else if (rnum1 === 56) third = "4";
  else if (rnum1 === 57) third = "5";
  else if (rnum1 === 58) third = "6";
  else if (rnum1 === 59) third = "7";
  else if (rnum1 === 60) third = "8";
  else if (rnum1 === 61) third = "9";
  else if (rnum1 === 62) third = "!";
  else if (rnum1 === 63) third = "@";
  else if (rnum1 === 64) third = "#";
  else if (rnum1 === 65) third = "$";
  else if (rnum1 === 66) third = "%";
  else if (rnum1 === 67) third = "^";
  else if (rnum1 === 68) third = "&";
  else if (rnum1 === 69) third= "*";
  else if (rnum1 === 70) third = "(";
  else if (rnum1 === 71) third = ")";
  else if (rnum1 === 72) third = "-";
  else if (rnum1 === 73) third = "=";
  else if (rnum1 === 74) third = "_";
  else if (rnum1 === 75) third = "+";
  else if (rnum1 === 76) third = "[";
  else if (rnum1 === 77) third = "]";
  else if (rnum1 === 78) third = "{";
  else if (rnum1 === 79) third = "}";
  else if (rnum1 === 80) third = "|";
  else if (rnum1 === 81) third = ";";
  else if (rnum1 === 82) third = ":";
  else if (rnum1 === 83) third = "'";
  else if (rnum1 === 84) third = "<";
  else if (rnum1 === 85) third = ">";
  else if (rnum1 === 86) third = ",";
  else if (rnum1 === 87) third = ".";
  else if (rnum1 === 88) third = "/";
  else if (rnum1 === 89) third = "?";

  generateFourth()
}

function generateFourth(){
  console.log("generatefourth");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) fourth = "a";
  else if (rnum1 === 1) fourth = "b";
  else if (rnum1 === 2) fourth = "c";
  else if (rnum1 === 3) fourth = "d";
  else if (rnum1 === 4) fourth = "e";
  else if (rnum1 === 5) fourth = "f";
  else if (rnum1 === 6) fourth = "g";
  else if (rnum1 === 7) fourth = "h";
  else if (rnum1 === 8) fourth = "i";
  else if (rnum1 === 9) fourth = "j";
  else if (rnum1 === 10) fourth = "k";
  else if (rnum1 === 11) fourth = "l";
  else if (rnum1 === 12) fourth = "m";
  else if (rnum1 === 13) fourth = "n";
  else if (rnum1 === 14) fourth = "o";
  else if (rnum1 === 15) fourth = "p";
  else if (rnum1 === 16) fourth = "q";
  else if (rnum1 === 17) fourth = "r";
  else if (rnum1 === 18) fourth = "s";
  else if (rnum1 === 19) fourth = "t";
  else if (rnum1 === 20) fourth = "u";
  else if (rnum1 === 21) fourth = "v";
  else if (rnum1 === 22) fourth = "w";
  else if (rnum1 === 23) fourth = "x";
  else if (rnum1 === 24) fourth = "y";
  else if (rnum1 === 25) fourth = "z";
  else if (rnum1 === 26) fourth = "A";
  else if (rnum1 === 27) fourth = "B";
  else if (rnum1 === 28) fourth = "C";
  else if (rnum1 === 29) fourth = "D";
  else if (rnum1 === 30) fourth = "E";
  else if (rnum1 === 31) fourth = "F";
  else if (rnum1 === 32) fourth = "G";
  else if (rnum1 === 33) fourth = "H";
  else if (rnum1 === 34) fourth = "I";
  else if (rnum1 === 35) fourth = "J";
  else if (rnum1 === 36) fourth = "K";
  else if (rnum1 === 37) fourth = "L";
  else if (rnum1 === 38) fourth = "M";
  else if (rnum1 === 39) fourth = "N";
  else if (rnum1 === 40) fourth = "O";
  else if (rnum1 === 41) fourth = "P";
  else if (rnum1 === 42) fourth = "Q";
  else if (rnum1 === 43) fourth = "R";
  else if (rnum1 === 44) fourth = "S";
  else if (rnum1 === 45) fourth = "T";
  else if (rnum1 === 46) fourth = "U";
  else if (rnum1 === 47) fourth = "V";
  else if (rnum1 === 48) fourth = "W";
  else if (rnum1 === 49) fourth = "X";
  else if (rnum1 === 50) fourth = "Y";
  else if (rnum1 === 51) fourth = "Z";
  else if (rnum1 === 52) fourth = "0";
  else if (rnum1 === 53) fourth = "1";
  else if (rnum1 === 54) fourth = "2";
  else if (rnum1 === 55) fourth = "3";
  else if (rnum1 === 56) fourth = "4";
  else if (rnum1 === 57) fourth = "5";
  else if (rnum1 === 58) fourth = "6";
  else if (rnum1 === 59) fourth = "7";
  else if (rnum1 === 60) fourth = "8";
  else if (rnum1 === 61) fourth = "9";
  else if (rnum1 === 62) fourth = "!";
  else if (rnum1 === 63) fourth = "@";
  else if (rnum1 === 64) fourth = "#";
  else if (rnum1 === 65) fourth = "$";
  else if (rnum1 === 66) fourth = "%";
  else if (rnum1 === 67) fourth = "^";
  else if (rnum1 === 68) fourth = "&";
  else if (rnum1 === 69) fourth= "*";
  else if (rnum1 === 70) fourth = "(";
  else if (rnum1 === 71) fourth = ")";
  else if (rnum1 === 72) fourth = "-";
  else if (rnum1 === 73) fourth = "=";
  else if (rnum1 === 74) fourth = "_";
  else if (rnum1 === 75) fourth = "+";
  else if (rnum1 === 76) fourth = "[";
  else if (rnum1 === 77) fourth = "]";
  else if (rnum1 === 78) fourth = "{";
  else if (rnum1 === 79) fourth = "}";
  else if (rnum1 === 80) fourth = "|";
  else if (rnum1 === 81) fourth = ";";
  else if (rnum1 === 82) fourth = ":";
  else if (rnum1 === 83) fourth = "'";
  else if (rnum1 === 84) fourth = "<";
  else if (rnum1 === 85) fourth = ">";
  else if (rnum1 === 86) fourth = ",";
  else if (rnum1 === 87) fourth = ".";
  else if (rnum1 === 88) fourth = "/";
  else if (rnum1 === 89) fourth = "?";

  generateFifth()
}

function generateFifth(){
  console.log("generateFifth");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) fifth = "a";
  else if (rnum1 === 1) fifth = "b";
  else if (rnum1 === 2) fifth = "c";
  else if (rnum1 === 3) fifth = "d";
  else if (rnum1 === 4) fifth = "e";
  else if (rnum1 === 5) fifth = "f";
  else if (rnum1 === 6) fifth = "g";
  else if (rnum1 === 7) fifth = "h";
  else if (rnum1 === 8) fifth = "i";
  else if (rnum1 === 9) fifth = "j";
  else if (rnum1 === 10) fifth = "k";
  else if (rnum1 === 11) fifth = "l";
  else if (rnum1 === 12) fifth = "m";
  else if (rnum1 === 13) fifth = "n";
  else if (rnum1 === 14) fifth = "o";
  else if (rnum1 === 15) fifth = "p";
  else if (rnum1 === 16) fifth = "q";
  else if (rnum1 === 17) fifth = "r";
  else if (rnum1 === 18) fifth = "s";
  else if (rnum1 === 19) fifth = "t";
  else if (rnum1 === 20) fifth = "u";
  else if (rnum1 === 21) fifth = "v";
  else if (rnum1 === 22) fifth = "w";
  else if (rnum1 === 23) fifth = "x";
  else if (rnum1 === 24) fifth = "y";
  else if (rnum1 === 25) fifth = "z";
  else if (rnum1 === 26) fifth = "A";
  else if (rnum1 === 27) fifth = "B";
  else if (rnum1 === 28) fifth = "C";
  else if (rnum1 === 29) fifth = "D";
  else if (rnum1 === 30) fifth = "E";
  else if (rnum1 === 31) fifth = "F";
  else if (rnum1 === 32) fifth = "G";
  else if (rnum1 === 33) fifth = "H";
  else if (rnum1 === 34) fifth = "I";
  else if (rnum1 === 35) fifth = "J";
  else if (rnum1 === 36) fifth = "K";
  else if (rnum1 === 37) fifth = "L";
  else if (rnum1 === 38) fifth = "M";
  else if (rnum1 === 39) fifth = "N";
  else if (rnum1 === 40) fifth = "O";
  else if (rnum1 === 41) fifth = "P";
  else if (rnum1 === 42) fifth = "Q";
  else if (rnum1 === 43) fifth = "R";
  else if (rnum1 === 44) fifth = "S";
  else if (rnum1 === 45) fifth = "T";
  else if (rnum1 === 46) fifth = "U";
  else if (rnum1 === 47) fifth = "V";
  else if (rnum1 === 48) fifth = "W";
  else if (rnum1 === 49) fifth = "X";
  else if (rnum1 === 50) fifth = "Y";
  else if (rnum1 === 51) fifth = "Z";
  else if (rnum1 === 52) fifth = "0";
  else if (rnum1 === 53) fifth = "1";
  else if (rnum1 === 54) fifth = "2";
  else if (rnum1 === 55) fifth = "3";
  else if (rnum1 === 56) fifth = "4";
  else if (rnum1 === 57) fifth = "5";
  else if (rnum1 === 58) fifth = "6";
  else if (rnum1 === 59) fifth = "7";
  else if (rnum1 === 60) fifth = "8";
  else if (rnum1 === 61) fifth = "9";
  else if (rnum1 === 62) fifth = "!";
  else if (rnum1 === 63) fifth = "@";
  else if (rnum1 === 64) fifth = "#";
  else if (rnum1 === 65) fifth = "$";
  else if (rnum1 === 66) fifth = "%";
  else if (rnum1 === 67) fifth = "^";
  else if (rnum1 === 68) fifth = "&";
  else if (rnum1 === 69) fifth= "*";
  else if (rnum1 === 70) fifth = "(";
  else if (rnum1 === 71) fifth = ")";
  else if (rnum1 === 72) fifth = "-";
  else if (rnum1 === 73) fifth = "=";
  else if (rnum1 === 74) fifth = "_";
  else if (rnum1 === 75) fifth = "+";
  else if (rnum1 === 76) fifth = "[";
  else if (rnum1 === 77) fifth = "]";
  else if (rnum1 === 78) fifth = "{";
  else if (rnum1 === 79) fifth = "}";
  else if (rnum1 === 80) fifth = "|";
  else if (rnum1 === 81) fifth = ";";
  else if (rnum1 === 82) fifth = ":";
  else if (rnum1 === 83) fifth = "'";
  else if (rnum1 === 84) fifth = "<";
  else if (rnum1 === 85) fifth = ">";
  else if (rnum1 === 86) fifth = ",";
  else if (rnum1 === 87) fifth = ".";
  else if (rnum1 === 88) fifth = "/";
  else if (rnum1 === 89) fifth = "?";

  generateSixth()
}

function generateSixth(){
  console.log("generateSixth");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) sixth = "a";
  else if (rnum1 === 1) sixth = "b";
  else if (rnum1 === 2) sixth = "c";
  else if (rnum1 === 3) sixth = "d";
  else if (rnum1 === 4) sixth = "e";
  else if (rnum1 === 5) sixth = "f";
  else if (rnum1 === 6) sixth = "g";
  else if (rnum1 === 7) sixth = "h";
  else if (rnum1 === 8) sixth = "i";
  else if (rnum1 === 9) sixth = "j";
  else if (rnum1 === 10) sixth = "k";
  else if (rnum1 === 11) sixth = "l";
  else if (rnum1 === 12) sixth = "m";
  else if (rnum1 === 13) sixth = "n";
  else if (rnum1 === 14) sixth = "o";
  else if (rnum1 === 15) sixth = "p";
  else if (rnum1 === 16) sixth = "q";
  else if (rnum1 === 17) sixth = "r";
  else if (rnum1 === 18) sixth = "s";
  else if (rnum1 === 19) sixth = "t";
  else if (rnum1 === 20) sixth = "u";
  else if (rnum1 === 21) sixth = "v";
  else if (rnum1 === 22) sixth = "w";
  else if (rnum1 === 23) sixth = "x";
  else if (rnum1 === 24) sixth = "y";
  else if (rnum1 === 25) sixth = "z";
  else if (rnum1 === 26) sixth = "A";
  else if (rnum1 === 27) sixth = "B";
  else if (rnum1 === 28) sixth = "C";
  else if (rnum1 === 29) sixth = "D";
  else if (rnum1 === 30) sixth = "E";
  else if (rnum1 === 31) sixth = "F";
  else if (rnum1 === 32) sixth = "G";
  else if (rnum1 === 33) sixth = "H";
  else if (rnum1 === 34) sixth = "I";
  else if (rnum1 === 35) sixth = "J";
  else if (rnum1 === 36) sixth = "K";
  else if (rnum1 === 37) sixth = "L";
  else if (rnum1 === 38) sixth = "M";
  else if (rnum1 === 39) sixth = "N";
  else if (rnum1 === 40) sixth = "O";
  else if (rnum1 === 41) sixth = "P";
  else if (rnum1 === 42) sixth = "Q";
  else if (rnum1 === 43) sixth = "R";
  else if (rnum1 === 44) sixth = "S";
  else if (rnum1 === 45) sixth = "T";
  else if (rnum1 === 46) sixth = "U";
  else if (rnum1 === 47) sixth = "V";
  else if (rnum1 === 48) sixth = "W";
  else if (rnum1 === 49) sixth = "X";
  else if (rnum1 === 50) sixth = "Y";
  else if (rnum1 === 51) sixth = "Z";
  else if (rnum1 === 52) sixth = "0";
  else if (rnum1 === 53) sixth = "1";
  else if (rnum1 === 54) sixth = "2";
  else if (rnum1 === 55) sixth = "3";
  else if (rnum1 === 56) sixth = "4";
  else if (rnum1 === 57) sixth = "5";
  else if (rnum1 === 58) sixth = "6";
  else if (rnum1 === 59) sixth = "7";
  else if (rnum1 === 60) sixth = "8";
  else if (rnum1 === 61) sixth = "9";
  else if (rnum1 === 62) sixth = "!";
  else if (rnum1 === 63) sixth = "@";
  else if (rnum1 === 64) sixth = "#";
  else if (rnum1 === 65) sixth = "$";
  else if (rnum1 === 66) sixth = "%";
  else if (rnum1 === 67) sixth = "^";
  else if (rnum1 === 68) sixth = "&";
  else if (rnum1 === 69) sixth= "*";
  else if (rnum1 === 70) sixth = "(";
  else if (rnum1 === 71) sixth = ")";
  else if (rnum1 === 72) sixth = "-";
  else if (rnum1 === 73) sixth = "=";
  else if (rnum1 === 74) sixth = "_";
  else if (rnum1 === 75) sixth = "+";
  else if (rnum1 === 76) sixth = "[";
  else if (rnum1 === 77) sixth = "]";
  else if (rnum1 === 78) sixth = "{";
  else if (rnum1 === 79) sixth = "}";
  else if (rnum1 === 80) sixth = "|";
  else if (rnum1 === 81) sixth = ";";
  else if (rnum1 === 82) sixth = ":";
  else if (rnum1 === 83) sixth = "'";
  else if (rnum1 === 84) sixth = "<";
  else if (rnum1 === 85) sixth = ">";
  else if (rnum1 === 86) sixth = ",";
  else if (rnum1 === 87) sixth = ".";
  else if (rnum1 === 88) sixth = "/";
  else if (rnum1 === 89) sixth = "?";

  generateSeveth()
}

function generateSeveth(){
  console.log("generateSeventh");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) seventh = "a";
  else if (rnum1 === 1) seventh = "b";
  else if (rnum1 === 2) seventh = "c";
  else if (rnum1 === 3) seventh = "d";
  else if (rnum1 === 4) seventh = "e";
  else if (rnum1 === 5) seventh = "f";
  else if (rnum1 === 6) seventh = "g";
  else if (rnum1 === 7) seventh = "h";
  else if (rnum1 === 8) seventh = "i";
  else if (rnum1 === 9) seventh = "j";
  else if (rnum1 === 10) seventh = "k";
  else if (rnum1 === 11) seventh = "l";
  else if (rnum1 === 12) seventh = "m";
  else if (rnum1 === 13) seventh = "n";
  else if (rnum1 === 14) seventh = "o";
  else if (rnum1 === 15) seventh = "p";
  else if (rnum1 === 16) seventh = "q";
  else if (rnum1 === 17) seventh = "r";
  else if (rnum1 === 18) seventh = "s";
  else if (rnum1 === 19) seventh = "t";
  else if (rnum1 === 20) seventh = "u";
  else if (rnum1 === 21) seventh = "v";
  else if (rnum1 === 22) seventh = "w";
  else if (rnum1 === 23) seventh = "x";
  else if (rnum1 === 24) seventh = "y";
  else if (rnum1 === 25) seventh = "z";
  else if (rnum1 === 26) seventh = "A";
  else if (rnum1 === 27) seventh = "B";
  else if (rnum1 === 28) seventh = "C";
  else if (rnum1 === 29) seventh = "D";
  else if (rnum1 === 30) seventh = "E";
  else if (rnum1 === 31) seventh = "F";
  else if (rnum1 === 32) seventh = "G";
  else if (rnum1 === 33) seventh = "H";
  else if (rnum1 === 34) seventh = "I";
  else if (rnum1 === 35) seventh = "J";
  else if (rnum1 === 36) seventh = "K";
  else if (rnum1 === 37) seventh = "L";
  else if (rnum1 === 38) seventh = "M";
  else if (rnum1 === 39) seventh = "N";
  else if (rnum1 === 40) seventh = "O";
  else if (rnum1 === 41) seventh = "P";
  else if (rnum1 === 42) seventh = "Q";
  else if (rnum1 === 43) seventh = "R";
  else if (rnum1 === 44) seventh = "S";
  else if (rnum1 === 45) seventh = "T";
  else if (rnum1 === 46) seventh = "U";
  else if (rnum1 === 47) seventh = "V";
  else if (rnum1 === 48) seventh = "W";
  else if (rnum1 === 49) seventh = "X";
  else if (rnum1 === 50) seventh = "Y";
  else if (rnum1 === 51) seventh = "Z";
  else if (rnum1 === 52) seventh = "0";
  else if (rnum1 === 53) seventh = "1";
  else if (rnum1 === 54) seventh = "2";
  else if (rnum1 === 55) seventh = "3";
  else if (rnum1 === 56) seventh = "4";
  else if (rnum1 === 57) seventh = "5";
  else if (rnum1 === 58) seventh = "6";
  else if (rnum1 === 59) seventh = "7";
  else if (rnum1 === 60) seventh = "8";
  else if (rnum1 === 61) seventh = "9";
  else if (rnum1 === 62) seventh = "!";
  else if (rnum1 === 63) seventh = "@";
  else if (rnum1 === 64) seventh = "#";
  else if (rnum1 === 65) seventh = "$";
  else if (rnum1 === 66) seventh = "%";
  else if (rnum1 === 67) seventh = "^";
  else if (rnum1 === 68) seventh = "&";
  else if (rnum1 === 69) seventh= "*";
  else if (rnum1 === 70) seventh = "(";
  else if (rnum1 === 71) seventh = ")";
  else if (rnum1 === 72) seventh = "-";
  else if (rnum1 === 73) seventh = "=";
  else if (rnum1 === 74) seventh = "_";
  else if (rnum1 === 75) seventh = "+";
  else if (rnum1 === 76) seventh = "[";
  else if (rnum1 === 77) seventh = "]";
  else if (rnum1 === 78) seventh = "{";
  else if (rnum1 === 79) seventh = "}";
  else if (rnum1 === 80) seventh = "|";
  else if (rnum1 === 81) seventh = ";";
  else if (rnum1 === 82) seventh = ":";
  else if (rnum1 === 83) seventh = "'";
  else if (rnum1 === 84) seventh = "<";
  else if (rnum1 === 85) seventh = ">";
  else if (rnum1 === 86) seventh = ",";
  else if (rnum1 === 87) seventh = ".";
  else if (rnum1 === 88) seventh = "/";
  else if (rnum1 === 89) seventh = "?";

  generateEighth()
}

function generateEighth(){
  console.log("generateEighth");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) eighth = "a";
  else if (rnum1 === 1) eighth = "b";
  else if (rnum1 === 2) eighth = "c";
  else if (rnum1 === 3) eighth = "d";
  else if (rnum1 === 4) eighth = "e";
  else if (rnum1 === 5) eighth = "f";
  else if (rnum1 === 6) eighth = "g";
  else if (rnum1 === 7) eighth = "h";
  else if (rnum1 === 8) eighth = "i";
  else if (rnum1 === 9) eighth = "j";
  else if (rnum1 === 10) eighth = "k";
  else if (rnum1 === 11) eighth = "l";
  else if (rnum1 === 12) eighth = "m";
  else if (rnum1 === 13) eighth = "n";
  else if (rnum1 === 14) eighth = "o";
  else if (rnum1 === 15) eighth = "p";
  else if (rnum1 === 16) eighth = "q";
  else if (rnum1 === 17) eighth = "r";
  else if (rnum1 === 18) eighth = "s";
  else if (rnum1 === 19) eighth = "t";
  else if (rnum1 === 20) eighth = "u";
  else if (rnum1 === 21) eighth = "v";
  else if (rnum1 === 22) eighth = "w";
  else if (rnum1 === 23) eighth = "x";
  else if (rnum1 === 24) eighth = "y";
  else if (rnum1 === 25) eighth = "z";
  else if (rnum1 === 26) eighth = "A";
  else if (rnum1 === 27) eighth = "B";
  else if (rnum1 === 28) eighth = "C";
  else if (rnum1 === 29) eighth = "D";
  else if (rnum1 === 30) eighth = "E";
  else if (rnum1 === 31) eighth = "F";
  else if (rnum1 === 32) eighth = "G";
  else if (rnum1 === 33) eighth = "H";
  else if (rnum1 === 34) eighth = "I";
  else if (rnum1 === 35) eighth = "J";
  else if (rnum1 === 36) eighth = "K";
  else if (rnum1 === 37) eighth = "L";
  else if (rnum1 === 38) eighth = "M";
  else if (rnum1 === 39) eighth = "N";
  else if (rnum1 === 40) eighth = "O";
  else if (rnum1 === 41) eighth = "P";
  else if (rnum1 === 42) eighth = "Q";
  else if (rnum1 === 43) eighth = "R";
  else if (rnum1 === 44) eighth = "S";
  else if (rnum1 === 45) eighth = "T";
  else if (rnum1 === 46) eighth = "U";
  else if (rnum1 === 47) eighth = "V";
  else if (rnum1 === 48) eighth = "W";
  else if (rnum1 === 49) eighth = "X";
  else if (rnum1 === 50) eighth = "Y";
  else if (rnum1 === 51) eighth = "Z";
  else if (rnum1 === 52) eighth = "0";
  else if (rnum1 === 53) eighth = "1";
  else if (rnum1 === 54) eighth = "2";
  else if (rnum1 === 55) eighth = "3";
  else if (rnum1 === 56) eighth = "4";
  else if (rnum1 === 57) eighth = "5";
  else if (rnum1 === 58) eighth = "6";
  else if (rnum1 === 59) eighth = "7";
  else if (rnum1 === 60) eighth = "8";
  else if (rnum1 === 61) eighth = "9";
  else if (rnum1 === 62) eighth = "!";
  else if (rnum1 === 63) eighth = "@";
  else if (rnum1 === 64) eighth = "#";
  else if (rnum1 === 65) eighth = "$";
  else if (rnum1 === 66) eighth = "%";
  else if (rnum1 === 67) eighth = "^";
  else if (rnum1 === 68) eighth = "&";
  else if (rnum1 === 69) eighth= "*";
  else if (rnum1 === 70) eighth = "(";
  else if (rnum1 === 71) eighth = ")";
  else if (rnum1 === 72) eighth = "-";
  else if (rnum1 === 73) eighth = "=";
  else if (rnum1 === 74) eighth = "_";
  else if (rnum1 === 75) eighth = "+";
  else if (rnum1 === 76) eighth = "[";
  else if (rnum1 === 77) eighth = "]";
  else if (rnum1 === 78) eighth = "{";
  else if (rnum1 === 79) eighth = "}";
  else if (rnum1 === 80) eighth = "|";
  else if (rnum1 === 81) eighth = ";";
  else if (rnum1 === 82) eighth = ":";
  else if (rnum1 === 83) eighth = "'";
  else if (rnum1 === 84) eighth = "<";
  else if (rnum1 === 85) eighth = ">";
  else if (rnum1 === 86) eighth = ",";
  else if (rnum1 === 87) eighth = ".";
  else if (rnum1 === 88) eighth = "/";
  else if (rnum1 === 89) eighth = "?";

  generateNineth()
}

function generateNineth(){
  console.log("generateNineth");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) nineth = "a";
  else if (rnum1 === 1) nineth = "b";
  else if (rnum1 === 2) nineth = "c";
  else if (rnum1 === 3) nineth = "d";
  else if (rnum1 === 4) nineth = "e";
  else if (rnum1 === 5) nineth = "f";
  else if (rnum1 === 6) nineth = "g";
  else if (rnum1 === 7) nineth = "h";
  else if (rnum1 === 8) nineth = "i";
  else if (rnum1 === 9) nineth = "j";
  else if (rnum1 === 10) nineth = "k";
  else if (rnum1 === 11) nineth = "l";
  else if (rnum1 === 12) nineth = "m";
  else if (rnum1 === 13) nineth = "n";
  else if (rnum1 === 14) nineth = "o";
  else if (rnum1 === 15) nineth = "p";
  else if (rnum1 === 16) nineth = "q";
  else if (rnum1 === 17) nineth = "r";
  else if (rnum1 === 18) nineth = "s";
  else if (rnum1 === 19) nineth = "t";
  else if (rnum1 === 20) nineth = "u";
  else if (rnum1 === 21) nineth = "v";
  else if (rnum1 === 22) nineth = "w";
  else if (rnum1 === 23) nineth = "x";
  else if (rnum1 === 24) nineth = "y";
  else if (rnum1 === 25) nineth = "z";
  else if (rnum1 === 26) nineth = "A";
  else if (rnum1 === 27) nineth = "B";
  else if (rnum1 === 28) nineth = "C";
  else if (rnum1 === 29) nineth = "D";
  else if (rnum1 === 30) nineth = "E";
  else if (rnum1 === 31) nineth = "F";
  else if (rnum1 === 32) nineth = "G";
  else if (rnum1 === 33) nineth = "H";
  else if (rnum1 === 34) nineth = "I";
  else if (rnum1 === 35) nineth = "J";
  else if (rnum1 === 36) nineth = "K";
  else if (rnum1 === 37) nineth = "L";
  else if (rnum1 === 38) nineth = "M";
  else if (rnum1 === 39) nineth = "N";
  else if (rnum1 === 40) nineth = "O";
  else if (rnum1 === 41) nineth = "P";
  else if (rnum1 === 42) nineth = "Q";
  else if (rnum1 === 43) nineth = "R";
  else if (rnum1 === 44) nineth = "S";
  else if (rnum1 === 45) nineth = "T";
  else if (rnum1 === 46) nineth = "U";
  else if (rnum1 === 47) nineth = "V";
  else if (rnum1 === 48) nineth = "W";
  else if (rnum1 === 49) nineth = "X";
  else if (rnum1 === 50) nineth = "Y";
  else if (rnum1 === 51) nineth = "Z";
  else if (rnum1 === 52) nineth = "0";
  else if (rnum1 === 53) nineth = "1";
  else if (rnum1 === 54) nineth = "2";
  else if (rnum1 === 55) nineth = "3";
  else if (rnum1 === 56) nineth = "4";
  else if (rnum1 === 57) nineth = "5";
  else if (rnum1 === 58) nineth = "6";
  else if (rnum1 === 59) nineth = "7";
  else if (rnum1 === 60) nineth = "8";
  else if (rnum1 === 61) nineth = "9";
  else if (rnum1 === 62) nineth = "!";
  else if (rnum1 === 63) nineth = "@";
  else if (rnum1 === 64) nineth = "#";
  else if (rnum1 === 65) nineth = "$";
  else if (rnum1 === 66) nineth = "%";
  else if (rnum1 === 67) nineth = "^";
  else if (rnum1 === 68) nineth = "&";
  else if (rnum1 === 69) nineth= "*";
  else if (rnum1 === 70) nineth = "(";
  else if (rnum1 === 71) nineth = ")";
  else if (rnum1 === 72) nineth = "-";
  else if (rnum1 === 73) nineth = "=";
  else if (rnum1 === 74) nineth = "_";
  else if (rnum1 === 75) nineth = "+";
  else if (rnum1 === 76) nineth = "[";
  else if (rnum1 === 77) nineth = "]";
  else if (rnum1 === 78) nineth = "{";
  else if (rnum1 === 79) nineth = "}";
  else if (rnum1 === 80) nineth = "|";
  else if (rnum1 === 81) nineth = ";";
  else if (rnum1 === 82) nineth = ":";
  else if (rnum1 === 83) nineth = "'";
  else if (rnum1 === 84) nineth = "<";
  else if (rnum1 === 85) nineth = ">";
  else if (rnum1 === 86) nineth = ",";
  else if (rnum1 === 87) nineth = ".";
  else if (rnum1 === 88) nineth = "/";
  else if (rnum1 === 89) nineth = "?";

  generateTenth()
}

function generateTenth(){
  console.log("generateTenth");
  var rnum1 = Math.floor(Math.random()*90);

  if (rnum1 === 0) tenth = "a";
  else if (rnum1 === 1) tenth = "b";
  else if (rnum1 === 2) tenth = "c";
  else if (rnum1 === 3) tenth = "d";
  else if (rnum1 === 4) tenth = "e";
  else if (rnum1 === 5) tenth = "f";
  else if (rnum1 === 6) tenth = "g";
  else if (rnum1 === 7) tenth = "h";
  else if (rnum1 === 8) tenth = "i";
  else if (rnum1 === 9) tenth = "j";
  else if (rnum1 === 10) tenth = "k";
  else if (rnum1 === 11) tenth = "l";
  else if (rnum1 === 12) tenth = "m";
  else if (rnum1 === 13) tenth = "n";
  else if (rnum1 === 14) tenth = "o";
  else if (rnum1 === 15) tenth = "p";
  else if (rnum1 === 16) tenth = "q";
  else if (rnum1 === 17) tenth = "r";
  else if (rnum1 === 18) tenth = "s";
  else if (rnum1 === 19) tenth = "t";
  else if (rnum1 === 20) tenth = "u";
  else if (rnum1 === 21) tenth = "v";
  else if (rnum1 === 22) tenth = "w";
  else if (rnum1 === 23) tenth = "x";
  else if (rnum1 === 24) tenth = "y";
  else if (rnum1 === 25) tenth = "z";
  else if (rnum1 === 26) tenth = "A";
  else if (rnum1 === 27) tenth = "B";
  else if (rnum1 === 28) tenth = "C";
  else if (rnum1 === 29) tenth = "D";
  else if (rnum1 === 30) tenth = "E";
  else if (rnum1 === 31) tenth = "F";
  else if (rnum1 === 32) tenth = "G";
  else if (rnum1 === 33) tenth = "H";
  else if (rnum1 === 34) tenth = "I";
  else if (rnum1 === 35) tenth = "J";
  else if (rnum1 === 36) tenth = "K";
  else if (rnum1 === 37) tenth = "L";
  else if (rnum1 === 38) tenth = "M";
  else if (rnum1 === 39) tenth = "N";
  else if (rnum1 === 40) tenth = "O";
  else if (rnum1 === 41) tenth = "P";
  else if (rnum1 === 42) tenth = "Q";
  else if (rnum1 === 43) tenth = "R";
  else if (rnum1 === 44) tenth = "S";
  else if (rnum1 === 45) tenth = "T";
  else if (rnum1 === 46) tenth = "U";
  else if (rnum1 === 47) tenth = "V";
  else if (rnum1 === 48) tenth = "W";
  else if (rnum1 === 49) tenth = "X";
  else if (rnum1 === 50) tenth = "Y";
  else if (rnum1 === 51) tenth = "Z";
  else if (rnum1 === 52) tenth = "0";
  else if (rnum1 === 53) tenth = "1";
  else if (rnum1 === 54) tenth = "2";
  else if (rnum1 === 55) tenth = "3";
  else if (rnum1 === 56) tenth = "4";
  else if (rnum1 === 57) tenth = "5";
  else if (rnum1 === 58) tenth = "6";
  else if (rnum1 === 59) tenth = "7";
  else if (rnum1 === 60) tenth = "8";
  else if (rnum1 === 61) tenth = "9";
  else if (rnum1 === 62) tenth = "!";
  else if (rnum1 === 63) tenth = "@";
  else if (rnum1 === 64) tenth = "#";
  else if (rnum1 === 65) tenth = "$";
  else if (rnum1 === 66) tenth = "%";
  else if (rnum1 === 67) tenth = "^";
  else if (rnum1 === 68) tenth = "&";
  else if (rnum1 === 69) tenth= "*";
  else if (rnum1 === 70) tenth = "(";
  else if (rnum1 === 71) tenth = ")";
  else if (rnum1 === 72) tenth = "-";
  else if (rnum1 === 73) tenth = "=";
  else if (rnum1 === 74) tenth = "_";
  else if (rnum1 === 75) tenth = "+";
  else if (rnum1 === 76) tenth = "[";
  else if (rnum1 === 77) tenth = "]";
  else if (rnum1 === 78) tenth = "{";
  else if (rnum1 === 79) tenth = "}";
  else if (rnum1 === 80) tenth = "|";
  else if (rnum1 === 81) tenth = ";";
  else if (rnum1 === 82) tenth = ":";
  else if (rnum1 === 83) tenth = "'";
  else if (rnum1 === 84) tenth = "<";
  else if (rnum1 === 85) tenth = ">";
  else if (rnum1 === 86) tenth = ",";
  else if (rnum1 === 87) tenth = ".";
  else if (rnum1 === 88) tenth = "/";
  else if (rnum1 === 89) tenth = "?";

  passwordconnect()
}

function passwordconnect(){
  console.log(first+second+third+fourth+fifth+sixth+seventh+eighth+nineth+tenth);
  return;
}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
